# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab3 files/lab3_system.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}]

# IP: bd/System/ip/System_processing_system7_0_axi_periph_0/System_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==System_processing_system7_0_axi_periph_0}]

# IP: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# IP: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}]

# IP: bd/System/ip/System_xbar_1/System_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xbar_1 || ORIG_REF_NAME==System_xbar_1}]

# IP: bd/System/ip/System_led_ip_0_0/System_led_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_led_ip_0_0 || ORIG_REF_NAME==System_led_ip_0_0}]

# IP: bd/System/ip/System_axi_bram_ctrl_0_0/System_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_bram_ctrl_0_0 || ORIG_REF_NAME==System_axi_bram_ctrl_0_0}]

# IP: bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==System_axi_bram_ctrl_0_bram_0}]

# IP: bd/System/ip/System_auto_pc_24/System_auto_pc_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_24 || ORIG_REF_NAME==System_auto_pc_24}]

# IP: bd/System/ip/System_auto_pc_26/System_auto_pc_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_26 || ORIG_REF_NAME==System_auto_pc_26}]

# IP: bd/System/ip/System_matrix_ip_0_0/System_matrix_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_matrix_ip_0_0 || ORIG_REF_NAME==System_matrix_ip_0_0}]

# IP: bd/System/ip/System_auto_pc_36/System_auto_pc_36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_36 || ORIG_REF_NAME==System_auto_pc_36}]

# IP: bd/System/ip/System_auto_pc_37/System_auto_pc_37.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_37 || ORIG_REF_NAME==System_auto_pc_37}]

# IP: bd/System/ip/System_auto_pc_38/System_auto_pc_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_38 || ORIG_REF_NAME==System_auto_pc_38}]

# IP: bd/System/ip/System_auto_pc_39/System_auto_pc_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_39 || ORIG_REF_NAME==System_auto_pc_39}]

# IP: bd/System/ip/System_auto_pc_40/System_auto_pc_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_40 || ORIG_REF_NAME==System_auto_pc_40}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_xbar_1/System_xbar_1_ooc.xdc

# XDC: bd/System/ip/System_axi_bram_ctrl_0_0/System_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/System/ip/System_axi_bram_ctrl_0_bram_0/System_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_24/System_auto_pc_24_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_26/System_auto_pc_26_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_36/System_auto_pc_36_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_37/System_auto_pc_37_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_38/System_auto_pc_38_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_39/System_auto_pc_39_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_40/System_auto_pc_40_ooc.xdc

# XDC: bd/System/System_ooc.xdc
