# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0

add_files C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/System.bd
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_xbar_1/System_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/ip/System_auto_pc_5/System_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/System_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/System.bd]

read_vhdl C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/sources_1/bd/System/hdl/System_wrapper.vhd
read_xdc C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/constrs_1/imports/lab1/lab1.xdc
set_property used_in_implementation false [get_files C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/constrs_1/imports/lab1/lab1.xdc]

read_xdc C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/constrs_1/new/System_wrapper.xdc
set_property used_in_implementation false [get_files C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.srcs/constrs_1/new/System_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1/Lab1.data/wt [current_project]
set_property parent.project_dir C:/Users/ReneNilsson/Documents/GitHub/Xilinx/labs/Lab1 [current_project]
synth_design -top System_wrapper -part xc7z020clg484-1
write_checkpoint System_wrapper.dcp
report_utilization -file System_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb
